GET http://localhost:8000/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1ZmE5Y2ZkZTQ1YmQ5MTMzMGU5NTU0NyIsImlhdCI6MTcxMDkyNjAxMiwiZXhwIjoxNzEwOTI2MDcyfQ.3cN1hNP06bCVrK-kFXlIaIq9fDvqtR19dDSMGvYQCq8
### 
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "emailAddress": "hieutranminh61@gmail.com",
    "password": "122312asd"
}

###
POST http://localhost:8000/refreshToken
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJoaWV1dHJhbm1pbmg2MUBnbWFpbC5jb20iLCJwYXNzd29yZCI6IjEyMjMxMmFzZCIsImlhdCI6MTcxMDkyNTQ3M30.n99C1rpSmnPlnAvZYrDEVEnG1MrCP5yyOaSfrUKIv-M"
}

### 
POST http://localhost:8000/logout
Content-Type: application/json 

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbEFkZHJlc3MiOiJoaWV1dHJhbm1pbmg2MUBnbWFpbC5jb20gIiwicGFzc3dvcmQiOiIxMjIzMTJhc2QiLCJpYXQiOjE3MTA5NTgwMzh9.Zyc0KgBWYYKl2wZ3dSoF2axGW_pTVr-a3p0QmS2JAzI"
}